version: "3.8"
services:
  sf-panel:
    build: .
    container_name: sf-panel
    restart: unless-stopped
    environment:
      - DEPLOY_MODE=vps
      - PANEL_PORT=2087
      # - ADMIN_USER=admin
      # - ADMIN_PASS=ChangeMe123
      # - TG_BOT_TOKEN=
      # - TG_ADMIN_IDS=
    ports:
      - "2087:2087"     # پنل
      - "8443:8443"     # ← پورت هر اینباند را اینجا map کن
    volumes:
      - ./data:/data